// Single-file inline plugin.
//
// js13k-vite-plugins only inlines CSS/JS into index.html as a side effect of its
// Roadroller plugin. DESIGN.md 3 wants inlining unconditionally and Roadroller
// only when the JS is big enough to pay for its decoder (~8KB). So when Roadroller
// is off, this stands in for that step: same bundle surgery, no Packer.
import { minify as htmlMinify } from 'html-minifier-terser';

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export const HTML_MINIFY = {
  includeAutoGeneratedTags: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
  collapseWhitespace: true,
  collapseInlineTagWhitespace: true,
  removeEmptyAttributes: true,
  removeOptionalTags: true,
  sortAttributes: true,
  // Terser (via Vite) and Vite's CSS pipeline already ran. Re-minifying here would
  // undo the scoped property mangling, so both stay off.
  minifyJS: false,
  minifyCSS: false,
};

export function inlinePlugin() {
  return {
    name: 'oln:inline',
    apply: 'build',
    enforce: 'post',
    generateBundle: {
      order: 'post',
      async handler(_options, bundle) {
        const htmlKey = Object.keys(bundle).find((k) => k.endsWith('.html'));
        if (!htmlKey) return;
        const htmlAsset = bundle[htmlKey];
        let html = String(htmlAsset.source);

        for (const key of Object.keys(bundle)) {
          if (!key.endsWith('.css')) continue;
          const css = bundle[key];
          const fn = esc(css.fileName);
          html = html.replace(
            new RegExp(`<link\\s[^>]*?href\\s*=\\s*(?:"[./]*${fn}"|'[./]*${fn}'|[./]*${fn})[^>]*?>`),
            () => `<style>${String(css.source).trim()}</style>`
          );
          delete bundle[key];
        }

        for (const key of Object.keys(bundle)) {
          if (!key.endsWith('.js')) continue;
          const js = bundle[key];
          const before = html;
          html = html.replace(
            new RegExp(`<script[^>]*?${esc(js.fileName)}[^>]*?></script>`),
            // type=module is kept deliberately. Terser is configured with
            // mangle.module:true, which assumes module scope and implied strict
            // mode; emitting a classic script instead would leak every top-level
            // binding onto window under different semantics than it optimised for.
            () => `<script type="module">${js.code.trim()}</script>`
          );
          if (html === before) throw new Error(`inline: no script tag matched ${js.fileName}`);
          delete bundle[key];
        }

        htmlAsset.source = await htmlMinify(html, HTML_MINIFY);
      },
    },
  };
}
